version: '3.4'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    image: registry.imaaronnicetomeetyou.me/cookbook/ingredients-api:0.0.4
    ports:
      - "5000:80"
    environment:
      - COOKBOOK_MONGO_ADDRESS=host.docker.internal:27017
