version: '3.4'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
  ingredients:
    image: registry.imaaronnicetomeetyou.me/cookbook/ingredients-api:0.0.5
    ports:
      - "80"
    environment:
      - COOKBOOK_MONGO_ADDRESS=192.168.2.59:27017
  files:
    image: registry.imaaronnicetomeetyou.me/cookbook/file-api:latest
    ports:
      - "80"
    environment:
      - MONGO_SERVER=192.168.2.59:27017
    volumes:
      - ./data:/srv/cookbook/files
